// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQJLLqzSu63FuRaMq6ZYUgHMHkKP5K65g',
    appId: '1:205726275285:web:633a7d414eee7fefd9f45c',
    messagingSenderId: '205726275285',
    projectId: 'project-101-wit',
    authDomain: 'project-101-wit.firebaseapp.com',
    databaseURL: 'https://project-101-wit-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-101-wit.appspot.com',
    measurementId: 'G-WZKM598GT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT6s1qN14u2SNNgqDcc3Gr2lWpRETvluY',
    appId: '1:205726275285:android:5848b3925fdec3d3d9f45c',
    messagingSenderId: '205726275285',
    projectId: 'project-101-wit',
    databaseURL: 'https://project-101-wit-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-101-wit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeJype_fzanUrwpYyL1z0ZotVaMxsSsdA',
    appId: '1:205726275285:ios:2e7e1fc640e8f930d9f45c',
    messagingSenderId: '205726275285',
    projectId: 'project-101-wit',
    databaseURL: 'https://project-101-wit-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-101-wit.appspot.com',
    androidClientId: '205726275285-61avgm4mumpa1jujvr43543b8aij2urh.apps.googleusercontent.com',
    iosClientId: '205726275285-v9crvh86mqcpu36j7pvm0gjnac3nvjuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.wit101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeJype_fzanUrwpYyL1z0ZotVaMxsSsdA',
    appId: '1:205726275285:ios:2e7e1fc640e8f930d9f45c',
    messagingSenderId: '205726275285',
    projectId: 'project-101-wit',
    databaseURL: 'https://project-101-wit-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'project-101-wit.appspot.com',
    androidClientId: '205726275285-61avgm4mumpa1jujvr43543b8aij2urh.apps.googleusercontent.com',
    iosClientId: '205726275285-v9crvh86mqcpu36j7pvm0gjnac3nvjuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.wit101',
  );
}
